#服务配置
server:
  #端口
  port: 7077
  #服务编码
  tomcat:
    uri-encoding: UTF-8
#spring相关配置
spring:
  #应用配置
  application:
    #应用名称
    name: model-shop-producer
  main:
    allow-bean-definition-overriding: true
  redis:
    redisson:
      config: classpath:singleServerConfig.yaml
  cloud:
    alibaba:
      seata:
        tx-service-group: project_tx_group
  #数据源配置
  shardingsphere:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.112.77:3306/restkeeper-shop-0?useAffectedRows=true&serverTimezone=UTC
        username: root
        password: pass
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.112.77:3306/restkeeper-shop-1?useAffectedRows=true&serverTimezone=UTC
        username: root
        password: pass
    #分库分表
    sharding:
      tables:
        tab_order: #数据库中要分表的逻辑名
          actualDataNodes: ds${0..1}.tab_order_${0..1}
          databaseStrategy:
            inline:
              shardingColumn: sharding_id
              algorithmExpression: ds${sharding_id % 2}
          tableStrategy:
            inline:
              shardingColumn: order_no
              algorithmExpression: tab_order_${order_no % 2}
          keyGenerator:
            type: SNOWFLAKE
            column: id
        tab_order_item: #数据库中要分表的逻辑名
          actualDataNodes: ds${0..1}.tab_order_item_${0..1}
          databaseStrategy:
            inline:
              shardingColumn: sharding_id
              algorithmExpression: ds${sharding_id % 2}
          tableStrategy:
            inline:
              shardingColumn: product_order_no
              algorithmExpression: tab_order_item_${product_order_no % 2}
          keyGenerator:
            type: SNOWFLAKE
            column: id
      binding-tables:
        - tab_order
        - tab_order_item
      broadcast-tables:
        - tab_brand
        - tab_category
        - tab_dish
        - tab_dish_flavor
        - tab_printer
        - tab_printer_dish
        - tab_store
        - tab_table
        - tab_table_area
        - undo_log
      default-key-generator:
        type: SNOWFLAKE
        column: id
    props:
      sql.show: true
#mybatis配置
mybatis-plus:
  # MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.itheima.springcloud.pojo
  # 该配置请和 typeAliasesPackage 一起使用，如果配置了该属性，则仅仅会扫描路径下以该类作为父类的域对象 。
  type-aliases-super-type: com.itheima.restkeeper.basic.BasicPojo
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 驼峰下划线转换
    map-underscore-to-camel-case: true
    use-generated-keys: true
    default-statement-timeout: 60
    default-fetch-size: 100
  #忽略商户号表
  ignore-enterprise-tables:
    - tab_dish_flavor
    - tab_order_item
    - undo_log
  #忽略门店号表
  ignore-store-tables:
    - tab_dish_flavor
    - tab_brand
    - tab_order_item
    - tab_store
    - undo_log
seata:
  tx-service-group: project_tx_group
  enabled: true
  application-id: ${spring.application.name}
  enable-auto-data-source-proxy: false
  service:
    #这里的名字与file.conf中vgroup_project_tx_group = "default"相同
    vgroup-mapping:
      project_tx_group: default
    #这里的名字与file.conf中default.grouplist = "192.168.112.77:8091"相同
    grouplist:
      default: 192.168.112.77:9200
  config:
    type: nacos
    nacos:
      group: SEATA_GROUP
      server-addr: 192.168.112.77:8848
      username: nacos
      password: nacos
  registry:
    type: nacos
    nacos:
      group: SEATA_GROUP
      server-addr: 192.168.112.77:8848
      username: nacos
      password: nacos
dubbo:
  #dubbo应用服务定义
  application:
    #版本
    version: 1.0.0
    #日志
    logger: slf4j
  scan:
    #扫描路径
    base-packages: com.itheima.restkeeper
  registry:
    #注册中心
    address: spring-cloud://192.168.112.77
  #服务协议定义
  protocol:
    #服务协议名称
    name: dubbo
    #协议端口
    port: 27077
    #线程数
    threads: 200
    #dubbo调用日志
    accesslog: D:/logs/model-shop-producer-01.log
