#服务配置
server:
  #端口
  port: 7070
  #服务编码
  tomcat:
    uri-encoding: UTF-8
#spring相关配置
spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    alicloud:
      access-key: LTAI4G2g6WqYBZyZMovev1pd
      secret-key: 2Q4x5TpgHRP8Eo3ehQzCJxPteBl4R4
      oss:
        bucket-name: itheima-sh-oss
        endpoint: oss-cn-shanghai.aliyuncs.com
    stream:
      binders:
        rabbit-log:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.112.77
                port: 5672
                username: admin
                password: pass
                virtual-host: /
      # Binding 配置项，对应 BindingProperties Map
      bindings:
        log-input:
          destination: log-output-01 # 目的地。这里使用 RocketMQ Topic
          content-type: application/json # 内容格式。这里使用 JSON
          group: log-listen-group-log-output-01 # 消费者分组,命名规则：组名+topic名
  #数据源配置
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.112.77:3306/restkeeper-basic?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
      username: root
      password: pass
#mybatis配置
mybatis-plus:
  # MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.itheima.springcloud.pojo
  # 该配置请和 typeAliasesPackage 一起使用，如果配置了该属性，则仅仅会扫描路径下以该类作为父类的域对象 。
  type-aliases-super-type: com.itheima.restkeeper.basic.BasicPojo
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 驼峰下划线转换
    map-underscore-to-camel-case: true
    use-generated-keys: true
    default-statement-timeout: 60
    default-fetch-size: 100
  #忽略商户号表
  ignore-enterprise-tables:
    - tab_affix
    - tab_log_business
    - tab_data_dict
    - undo_log
  #忽略门店号表
  ignore-store-tables:
    - tab_affix
    - tab_log_business
    - tab_data_dict
    - undo_log